In [ ]:
# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`


In [1]:
import numpy as np

In [2]:
null_vector = np.zeros(10)
print(null_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
null_vector_fifth_one = np.zeros(10)
null_vector_fifth_one[4]=1
print(null_vector_fifth_one)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [12]:
matrix = np.arange(0, 9).reshape((3,3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
x = [1,2,0,0,4,0]
np.nonzero(x)

(array([0, 1, 4]),)

In [16]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
np.random.seed(50)
a = np.random.random((3,3,3))
a

array([[[0.49460165, 0.2280831 , 0.25547392],
        [0.39632991, 0.3773151 , 0.99657423],
        [0.4081972 , 0.77189399, 0.76053669]],

       [[0.31000935, 0.3465412 , 0.35176482],
        [0.14546686, 0.97266468, 0.90917844],
        [0.5599571 , 0.31359075, 0.88820004]],

       [[0.67457307, 0.39108745, 0.50718412],
        [0.5241035 , 0.92800093, 0.57137307],
        [0.66833757, 0.05225869, 0.3270573 ]]])

In [18]:
np.random.seed(50)
a2 = np.random.random((10,10))
a2

array([[0.49460165, 0.2280831 , 0.25547392, 0.39632991, 0.3773151 ,
        0.99657423, 0.4081972 , 0.77189399, 0.76053669, 0.31000935],
       [0.3465412 , 0.35176482, 0.14546686, 0.97266468, 0.90917844,
        0.5599571 , 0.31359075, 0.88820004, 0.67457307, 0.39108745],
       [0.50718412, 0.5241035 , 0.92800093, 0.57137307, 0.66833757,
        0.05225869, 0.3270573 , 0.05640164, 0.17982769, 0.92593317],
       [0.93801522, 0.71409271, 0.73268761, 0.46174768, 0.93132927,
        0.40642024, 0.68320577, 0.64991587, 0.59876518, 0.22203939],
       [0.68235717, 0.8780563 , 0.79671726, 0.43200225, 0.91787822,
        0.78183368, 0.72575028, 0.12485469, 0.91630845, 0.38771099],
       [0.29492955, 0.61673141, 0.46784623, 0.25533891, 0.83899589,
        0.1786192 , 0.22711417, 0.65987645, 0.47911625, 0.07344734],
       [0.13896007, 0.11230718, 0.47778497, 0.54029623, 0.95807105,
        0.58379231, 0.52666409, 0.92226269, 0.91925702, 0.25200886],
       [0.68263261, 0.96427612, 0.2269616

In [23]:
a2.max()

0.9965742301546493

In [24]:
a2.min()

0.005439868860820707

In [25]:
random_vector = np.random.random(10)
print(random_vector)

[0.04969769 0.46269203 0.40821902 0.48704348 0.07051578 0.58210861
 0.9870218  0.20908846 0.21237612 0.96113505]


In [26]:
np.mean(random_vector)

0.442989803045627

In [28]:
matrix_5_5 = np.diag([0, 1, 2, 3, 4])
print(matrix_5_5)

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


In [32]:
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x_normalized = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x_normalized)




Original Array:
[[0.2507041  0.1338797  0.15077408 0.93903034 0.97145289]
 [0.14255659 0.19586501 0.10039784 0.08181247 0.76837567]
 [0.21035674 0.46217645 0.08401004 0.33150228 0.9883258 ]
 [0.90027204 0.8653286  0.38426349 0.70058469 0.03712971]
 [0.50132622 0.11389309 0.73368983 0.4368208  0.32698639]]
After normalization:
[[0.22453246 0.10171404 0.11947523 0.94817529 0.98226137]
 [0.11083612 0.16687969 0.06651429 0.04697535 0.76876469]
 [0.18211496 0.44685501 0.04928566 0.30947623 1.        ]
 [0.90742839 0.87069207 0.36494451 0.69749549 0.        ]
 [0.48801348 0.08070195 0.73229918 0.42019842 0.30472863]]


In [33]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


In [35]:
vector_10 = np.random.random(10)
print("Original array:")
print(vector_10)
vector_10.sort()
print("Sorted array:")
print(vector_10)

Original array:
[0.17089731 0.97912486 0.77506927 0.97215536 0.52546288 0.23845432
 0.48513857 0.58924287 0.50048255 0.42967478]
Sorted array:
[0.17089731 0.23845432 0.42967478 0.48513857 0.50048255 0.52546288
 0.58924287 0.77506927 0.97215536 0.97912486]


In [36]:
vector_size_10 = np.random.random(10)
print("Original array:")
print(vector_size_10)
vector_size_10[vector_size_10.argmax()] = 0
print("Maximum value replaced by 0:")
print(vector_size_10)

Original array:
[0.25084904 0.05742958 0.64337086 0.25149514 0.19150807 0.51069737
 0.38072579 0.91691728 0.052225   0.37753971]
Maximum value replaced by 0:
[0.25084904 0.05742958 0.64337086 0.25149514 0.19150807 0.51069737
 0.38072579 0.         0.052225   0.37753971]


In [37]:
print("Original matrix:\n")
X = np.random.rand(8, 5)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.49772142 0.57934039 0.80754723 0.89250305 0.47214697]
 [0.09868776 0.72744521 0.48904438 0.70245153 0.35734982]
 [0.19376319 0.33751561 0.54651098 0.95891554 0.91596329]
 [0.70668843 0.86573918 0.22818281 0.80168487 0.73913011]
 [0.1946778  0.14734561 0.36728392 0.35041886 0.1108308 ]
 [0.17002922 0.65791153 0.94652336 0.25547056 0.10940926]
 [0.78507242 0.48882333 0.61202074 0.89824815 0.39116821]
 [0.10817416 0.31668102 0.02025084 0.59322155 0.5845152 ]]

Subtract the mean of each row of the said matrix:

[[-0.15213039 -0.07051142  0.15769542  0.24265123 -0.17770484]
 [-0.37630798  0.25244947  0.01404864  0.22745579 -0.11764592]
 [-0.39677053 -0.25301811 -0.04402274  0.36838182  0.32542957]
 [ 0.03840335  0.1974541  -0.44010227  0.13339979  0.07084503]
 [-0.0394336  -0.08676579  0.13317252  0.11630746 -0.1232806 ]
 [-0.25783956  0.23004274  0.51865457 -0.17239823 -0.31845952]
 [ 0.15000585 -0.14624324 -0.02304583  0.26318158 -0.24389837]
 [-0.2163944  -0.0078875

In [50]:
Z = np.arange(10000)
np.random.shuffle(Z)

print("Given array:", Z)
  
sorted_index_array = np.argsort(Z)
  
sorted_array = Z[sorted_index_array]
  
print("Sorted array:", sorted_array)
  
# we want 5 largest values
n = 5

top5 = np.argpartition(sorted_array, -n)[-n:]
print("5 largest values:", top5)

  


Given array: [5869 7826 9435 ... 2176 9884 7657]
Sorted array: [   0    1    2 ... 9997 9998 9999]
5 largest values: [9995 9996 9997 9998 9999]


In [ ]:
#18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
#`hint: np.where`
 

In [56]:
np.random.seed(0)
random_matrix = np.random.random((5,3))
print(random_matrix)



[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606]]


In [ ]:
np.where(random_matrix > 4, random_matrix, random_matrix**)

In [57]:
import pandas as pd